# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\форма_предметы.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3  #+++

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_itemsWindow(QtWidgets.QMainWindow):   #+++
    def __init__(self, action):
        super().__init__()
        self.action = action
        self.setupUi(self)
        self.setWindowTitle('Добавить')
        self.itemService = ItemService()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 170)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_saveitems = QtWidgets.QPushButton(self.centralwidget)
        self.Button_saveitems.setGeometry(QtCore.QRect(20, 75, 85, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_saveitems.setFont(font)
        self.Button_saveitems.setStyleSheet("background-color: rgb(196, 207, 255);")
        self.Button_saveitems.setObjectName("Button_saveitems")
        self.id_items = QtWidgets.QLabel(self.centralwidget)
        self.id_items.setGeometry(QtCore.QRect(10, 0, 250, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_items.setFont(font)
        self.id_items.setStyleSheet("background-color: rgb(196, 207, 255);")
        self.id_items.setAlignment(QtCore.Qt.AlignCenter)
        self.id_items.setObjectName("id_items")
        self.Name_items = QtWidgets.QLabel(self.centralwidget)
        self.Name_items.setGeometry(QtCore.QRect(270, 0, 250, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Name_items.setFont(font)
        self.Name_items.setStyleSheet("background-color: rgb(196, 207, 255);")
        self.Name_items.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_items.setObjectName("Name_items")
        self.input_id_items = QtWidgets.QLineEdit(self.centralwidget)
        self.input_id_items.setGeometry(QtCore.QRect(10, 35, 250, 30))
        self.input_id_items.setObjectName("input_id_items")
        self.input_items = QtWidgets.QLineEdit(self.centralwidget)
        self.input_items.setGeometry(QtCore.QRect(270, 35, 250, 30))
        self.input_items.setObjectName("input_items")
        MainWindow.setCentralWidget(self.centralwidget)

        self.Button_saveitems.clicked.connect(self.save) #+++

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_saveitems.setText(_translate("MainWindow", "Сохранить"))
        self.id_items.setText(_translate("MainWindow", "ID предмета"))
        self.Name_items.setText(_translate("MainWindow", "Название предмета"))

    def save(self):    #+++
        code = self.input_id_items.text()
        name = self.input_items.text()
        item = Item(code, name)  # в переменнудю профф положиди экземпляр клсса профф с кодом и именем
        self.itemService.save(item)     #отправиди профессию на сохранение
        self.action()
        self.close()


class ItemService:   #+++
    def __init__(self):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        cursor.execute('''CREATE TABLE IF NOT EXISTS Список_предметов(
                      номер_предмета INTEGER primary key, 
                      название_предмета TEXT)''')
        connection.commit()
        connection.close()

    def save(self, item): #+++
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        cursor.execute(f'''INSERT INTO Список_предметов VALUES ({item.code}, '{item.name}')''')
        resultset = cursor.execute(''' SELECT * FROM Список_предметов''')
        print(resultset.fetchall())
        connection.commit()
        connection.close()


class Item:
    def __init__(self, code, name):
        self.code = code
        self.name = name



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_itemsWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
