# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\специальности_профф.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfWindow(QtWidgets.QMainWindow): #++
    def __init__(self, action): #++
        super().__init__() #++
        self.action = action #++
        self.setupUi(self) #++
        self.setWindowTitle('Добавить') #++
        self.proffService = ProffService() #++

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 170)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_save_proff = QtWidgets.QPushButton(self.centralwidget)
        self.Button_save_proff.setGeometry(QtCore.QRect(20, 75, 85, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_save_proff.setFont(font)
        self.Button_save_proff.setStyleSheet("background-color: rgb(196, 207, 255);")
        self.Button_save_proff.setObjectName("pushButton")
        self.Label_idProff = QtWidgets.QLabel(self.centralwidget)
        self.Label_idProff.setGeometry(QtCore.QRect(10, 0, 250, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label_idProff.setFont(font)
        self.Label_idProff.setStyleSheet("background-color: rgb(196, 207, 255);")
        self.Label_idProff.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_idProff.setObjectName("label")
        self.label_NameProff = QtWidgets.QLabel(self.centralwidget)
        self.label_NameProff.setGeometry(QtCore.QRect(270, 0, 250, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_NameProff.setFont(font)
        self.label_NameProff.setStyleSheet("background-color: rgb(196, 207, 255);")
        self.label_NameProff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NameProff.setObjectName("label_2")
        self.input_codeProff = QtWidgets.QLineEdit(self.centralwidget)
        self.input_codeProff.setGeometry(QtCore.QRect(10, 35, 250, 30))
        self.input_codeProff.setObjectName("lineEdit")
        self.input_nameProff = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nameProff.setGeometry(QtCore.QRect(270, 35, 250, 30))
        self.input_nameProff.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.Button_save_proff.clicked.connect(self.save)  #++

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Редактор специальностей"))
        self.Button_save_proff.setText(_translate("MainWindow", "Сохранить"))
        self.Label_idProff.setText(_translate("MainWindow", "код специальности"))
        self.label_NameProff.setText(_translate("MainWindow", "Название специальности"))

    def save(self):
        code = self.input_codeProff.text()
        name = self.input_nameProff.text()
        proff = Proff(code, name)  # в переменнудю профф положиди экземпляр клсса профф с кодом и именем
        self.proffService.save(proff)     #отправиди профессию на сохранение
        self.action()
        self.close()


class ProffService:
    def __init__(self):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        cursor.execute('''CREATE TABLE IF NOT EXISTS Справочник_специальностей(
                      номер_специальности INTEGER primary key, 
                      название_специальности TEXT)''')
        connection.commit()
        connection.close()

    def save(self, proff):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        cursor.execute(f'''INSERT INTO Справочник_специальностей VALUES ({proff.code}, '{proff.name}')''')
        resultset = cursor.execute(''' SELECT * FROM Справочник_специальностей''')
        print(resultset.fetchall())
        connection.commit()
        connection.close()


class Proff:
    def __init__(self, code, name):
        self.code = code
        self.name = name



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ProfWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
