# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\меню_препода.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuChoice(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 650, 400))
        self.tabWidget.setStyleSheet("background-color: rgb(196, 207, 255);\n"
"selection-background-color: rgb(85, 85, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.proff = QtWidgets.QWidget()
        self.proff.setObjectName("proff")
        self.table_Proff = QtWidgets.QTableWidget(self.proff)
        self.table_Proff.setGeometry(QtCore.QRect(0, 50, 650, 400))
        self.table_Proff.setObjectName("table_Proff")
        self.table_Proff.setColumnCount(3)
        self.table_Proff.setRowCount(0)
        self.table_Proff.setHorizontalHeaderLabels(['ID специальности', 'Наименование специальности', 'Действия'])  #++
        self.table_Proff.resizeColumnsToContents() #++
        self.load_proff()  #++
        self.Button_Proff = QtWidgets.QPushButton(self.proff)
        self.Button_Proff.setGeometry(QtCore.QRect(20, 10, 80, 25))
        self.Button_Proff.setObjectName("Button_Proff")
        self.tabWidget.addTab(self.proff, "")


        self.items = QtWidgets.QWidget()
        self.items.setObjectName("items")
        self.table_Items = QtWidgets.QTableWidget(self.items)
        self.table_Items.setGeometry(QtCore.QRect(0, 50, 650, 400))
        self.table_Items.setObjectName("table_Items")
        self.table_Items.setColumnCount(3)
        self.table_Items.setRowCount(0)

        #item = QtWidgets.QTableWidgetItem()
        #self.table_Items.setHorizontalHeaderItem(0, item)
        #item = QtWidgets.QTableWidgetItem()
        #self.table_Items.setHorizontalHeaderItem(1, item)
        #item = QtWidgets.QTableWidgetItem()
        #self.table_Items.setHorizontalHeaderItem(2, item)
        self.table_Items.setHorizontalHeaderLabels(['ID предмета', 'Наименование предмета', 'Действия'])  # ++
        self.table_Items.resizeColumnsToContents()  # ++
        self.load_items()  # ++

        self.Button_Items = QtWidgets.QPushButton(self.items)
        self.Button_Items.setGeometry(QtCore.QRect(20, 10, 80, 25))
        self.Button_Items.setObjectName("Button_Items")
        self.tabWidget.addTab(self.items, "")


        self.Students = QtWidgets.QWidget()
        self.Students.setObjectName("Students")
        self.table_Students = QtWidgets.QTableWidget(self.Students)
        self.table_Students.setGeometry(QtCore.QRect(0, 50, 650, 220))
        self.table_Students.setObjectName("table_Students")
        self.table_Students.setColumnCount(5)
        self.table_Students.setRowCount(0)
        # item = QtWidgets.QTableWidgetItem()
        # self.table_Students.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table_Students.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table_Students.setHorizontalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table_Students.setHorizontalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table_Students.setHorizontalHeaderItem(4, item)
        self.table_Students.setHorizontalHeaderLabels(['ID', 'ФИО', 'Выбранная специальность', 'Наличие достижений',
                                                       'Действия'])  # ++
        self.table_Students.resizeColumnsToContents()  # ++
        self.load_anketas()  # ++

        self.Button_Students = QtWidgets.QPushButton(self.Students)
        self.Button_Students.setGeometry(QtCore.QRect(20, 10, 80, 25))
        self.Button_Students.setObjectName("Button_Students")
        self.tabWidget.addTab(self.Students, "")

        self.check_achievements = QtWidgets.QCheckBox(self.Students)
        self.check_achievements.setGeometry(QtCore.QRect(180, 10, 120, 25))
        self.check_achievements.setText("С достижениями")
        self.check_achievements.clicked.connect(lambda: self.load_anketas(self.check_achievements.isChecked()))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def add_table_line_proff(self, i, row):
        self.table_Proff.setRowCount(i+1)
        item = QtWidgets.QTableWidgetItem()
        item.setText(str(row[0]))
        self.table_Proff.setItem(i, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText(row[1])
        self.table_Proff.setItem(i, 1, item)
        item = QtWidgets.QTableWidgetItem()

        del_Button = QtWidgets.QPushButton(self.table_Proff)
        del_Button.setText('🗑')
        del_Button.clicked.connect(lambda: self.del_proff(row[0]))

        layout = QtWidgets.QHBoxLayout()
       # layout.addWidget(edit_Button)
        layout.addWidget(del_Button)
        layout.setContentsMargins(0, 0, 0, 0)
        widget = QtWidgets.QWidget()
        widget.setLayout(layout)
        self.table_Proff.setCellWidget(i, 2, widget)
        self.table_Proff.setItem(i, 2, item)

    def add_table_line_items(self, i, row):
        self.table_Items.setRowCount(i+1)
        item = QtWidgets.QTableWidgetItem()
        item.setText(str(row[0]))
        self.table_Items.setItem(i, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText(row[1])
        self.table_Items.setItem(i, 1, item)
        item = QtWidgets.QTableWidgetItem()
        #edit_Button = QtWidgets.QPushButton(self.table_Proff)
       # edit_Button.setText('🖉')
        del_Button = QtWidgets.QPushButton(self.table_Items)
        del_Button.setText('🗑')
        del_Button.clicked.connect(lambda: self.del_items(row[0]))

        layout = QtWidgets.QHBoxLayout()
       # layout.addWidget(edit_Button)
        layout.addWidget(del_Button)
        layout.setContentsMargins(0, 0, 0, 0)
        widget = QtWidgets.QWidget()
        widget.setLayout(layout)
        self.table_Items.setCellWidget(i, 2, widget)
        self.table_Items.setItem(i, 2, item)

    def add_table_line_anketa(self, i, row):
        self.table_Students.setRowCount(i+1)

        item = QtWidgets.QTableWidgetItem()
        item.setText(str(row[0]))
        self.table_Students.setItem(i, 0, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText(row[1])
        self.table_Students.setItem(i, 1, item)

        item = QtWidgets.QTableWidgetItem() #+++добавила
        item.setText(row[14])
        self.table_Students.setItem(i, 2, item)

        item = QtWidgets.QTableWidgetItem() #+++добавила
        item.setText('yes' if row[9] else'no')
        self.table_Students.setItem(i, 3, item)

        item = QtWidgets.QTableWidgetItem()
        del_Button = QtWidgets.QPushButton(self.table_Students)
        del_Button.setText('🗑')
        del_Button.clicked.connect(lambda: self.del_anketas(row[0]))

        layout = QtWidgets.QHBoxLayout()

        layout.addWidget(del_Button)
        layout.setContentsMargins(0, 0, 0, 0)
        widget = QtWidgets.QWidget()
        widget.setLayout(layout)
        self.table_Students.setCellWidget(i, 4, widget)
        self.table_Students.setItem(i, 4, item)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # item = self.table_Proff.verticalHeaderItem(0)
        # item.setText(_translate("MainWindow", "1"))
        # item = self.table_Proff.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "ID специальности"))
        # item = self.table_Proff.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "Наименование специальности"))
        # item = self.table_Proff.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "Действия"))
        __sortingEnabled = self.table_Proff.isSortingEnabled()
        self.table_Proff.setSortingEnabled(False)

        self.table_Proff.setSortingEnabled(__sortingEnabled)
        self.Button_Proff.setText(_translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.proff), _translate("MainWindow", "Специальности"))


        # item = self.table_Items.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "ID предмета"))
        # item = self.table_Items.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "Новый столбец"))
        # item = self.table_Items.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "Действия"))
        __sortingEnabled = self.table_Items.isSortingEnabled()
        self.table_Items.setSortingEnabled(False)

        self.table_Items.setSortingEnabled(__sortingEnabled)
        self.Button_Items.setText(_translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.items), _translate("MainWindow", "Предметы"))


        # item = self.table_Students.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "№"))
        # item = self.table_Students.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "ФИО"))
        # item = self.table_Students.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "Выбранная специальности"))
        # item = self.table_Students.horizontalHeaderItem(3)
        # item.setText(_translate("MainWindow", "Наличие достижений"))
        # item = self.table_Students.horizontalHeaderItem(4)
        # item.setText(_translate("MainWindow", "Действия"))
        __sortingEnabled = self.table_Students.isSortingEnabled()
        self.table_Students.setSortingEnabled(False)

        self.table_Students.setSortingEnabled(__sortingEnabled)
        self.Button_Students.setText(_translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Students), _translate("MainWindow", "Абитуриенты"))
#-------
    def load_proff(self):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        resultset = cursor.execute('''SELECT * FROM Справочник_специальностей''')
#        print(resultset.fetchall())
        rows = resultset.fetchall()
        for i, row in enumerate(rows):     #
            self.add_table_line_proff(i, row)
        connection.commit()
        connection.close()

    def del_proff(self, proff_code):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        cursor.execute(f'''DELETE  FROM Справочник_специальностей WHERE номер_специальности={proff_code}''')
        connection.commit()
        connection.close()
        self.load_proff()

#--------
    def load_items(self):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        resultset = cursor.execute('''SELECT * FROM Список_предметов''')
        rows = resultset.fetchall()
        for i, row in enumerate(rows):  #
            self.add_table_line_items(i, row)
        connection.commit()
        connection.close()

    def del_items(self, items_code):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        cursor.execute(f'''DELETE  FROM Список_предметов WHERE номер_предмета={items_code}''')
        connection.commit()
        connection.close()
        self.load_items()
#--------
    def load_anketas(self, withachievements = False):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()

        if withachievements:
            resultset = cursor.execute('''SELECT * FROM Список_абитуриентов WHERE достижения=1 
            ORDER BY выбранная_специальность, фамилия, имя, отчество ''')
        else:
            resultset = cursor.execute('''SELECT * FROM Список_абитуриентов ORDER BY выбранная_специальность, фамилия, имя, отчество ''')
        rows = resultset.fetchall()
        for i, row in enumerate(rows):
           self.add_table_line_anketa(i, row)
        connection.commit()
        connection.close()

    def del_anketas(self, anketas_code):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        cursor.execute(f'''DELETE  FROM Список_абитуриентов WHERE регистрационный_номер={anketas_code}''')
        connection.commit()
        connection.close()
        self.load_anketas()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MenuChoice()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
