# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\2anketa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from teacher_menu import Ui_MenuChoice

class Ui_Anketa(QtWidgets.QMainWindow):
    def __init__(self, action = None):
        super().__init__()
        self.action = action  # ++
        self.setupUi(self)  # ++
        self.setWindowTitle('Добавить')  # ++
        self.anketaService = AnketaService()  # ++

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 400, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(196, 207, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.check_achievements = QtWidgets.QCheckBox(self.centralwidget)
        self.check_achievements.setGeometry(QtCore.QRect(250, 310, 141, 31))
        self.check_achievements.setObjectName("checkBox")
        self.check_achievements.setChecked(True)
        self.input_surname = QtWidgets.QLineEdit(self.centralwidget)
        self.input_surname.setGeometry(QtCore.QRect(20, 75, 120, 25))
        self.input_surname.setText("Иванов")
        self.input_surname.setAlignment(QtCore.Qt.AlignCenter)
        self.input_surname.setObjectName("lineEdit")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(160, 75, 120, 25))
        self.input_name.setText("Иван")
        self.input_name.setObjectName("lineEdit_2")
        self.input_school_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_school_name.setGeometry(QtCore.QRect(160, 260, 120, 22))
        self.input_school_name.setText("СОШ")
        self.input_school_name.setObjectName("lineEdit_3")
        self.input_regnumber = QtWidgets.QLineEdit(self.centralwidget)
        self.input_regnumber.setGeometry(QtCore.QRect(230, 145, 190, 25))
        self.input_regnumber.setInputMask("9999") #trrrrrrrrrrrr
        self.input_regnumber.setText("")
        self.input_regnumber.setObjectName("lineEdit_4")
        self.input_birthday = QtWidgets.QDateEdit(self.centralwidget)
        self.input_birthday.setGeometry(QtCore.QRect(20, 145, 190, 25))
        #self.input_birthday.setText("")
        self.input_birthday.setObjectName("lineEdit_5")
        self.input_patronymic = QtWidgets.QLineEdit(self.centralwidget)
        self.input_patronymic.setGeometry(QtCore.QRect(300, 75, 120, 25))
        self.input_patronymic.setText("Иваныч")
        self.input_patronymic.setObjectName("lineEdit_6")
        self.input_school_city = QtWidgets.QLineEdit(self.centralwidget)
        self.input_school_city.setGeometry(QtCore.QRect(20, 260, 120, 25))
        self.input_school_city.setText("Санкт-Петербург")
        self.input_school_city.setObjectName("lineEdit_7")
        self.input_school_end = QtWidgets.QDateEdit(self.centralwidget)
        self.input_school_end.setGeometry(QtCore.QRect(20, 330, 120, 25))
        #self.input_school_end.setText("")
        self.input_school_end.setObjectName("lineEdit_8")
        self.input_city = QtWidgets.QLineEdit(self.centralwidget)
        self.input_city.setGeometry(QtCore.QRect(20, 445, 120, 25))
        self.input_city.setText("Москва")
        self.input_city.setObjectName("lineEdit_9")
        self.input_school_number = QtWidgets.QLineEdit(self.centralwidget)
        self.input_school_number.setGeometry(QtCore.QRect(300, 260, 120, 25))
        self.input_school_number.setText("5")
        self.input_school_number.setObjectName("lineEdit_10")
        self.input_street = QtWidgets.QLineEdit(self.centralwidget)
        self.input_street.setGeometry(QtCore.QRect(160, 445, 120, 25))
        self.input_street.setText("Ленина")
        self.input_street.setObjectName("lineEdit_11")
        self.input_telephone = QtWidgets.QLineEdit(self.centralwidget)
        self.input_telephone.setGeometry(QtCore.QRect(20, 515, 190, 25))
        self.input_telephone.setText("8128128125")
        self.input_telephone.setObjectName("lineEdit_12")
        self.input_number = QtWidgets.QLineEdit(self.centralwidget)
        self.input_number.setGeometry(QtCore.QRect(300, 445, 120, 25))
        self.input_number.setText("142")
        self.input_number.setObjectName("lineEdit_13")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 400, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(196, 207, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 375, 400, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(196, 207, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.label_surname = QtWidgets.QLabel(self.centralwidget)
        self.label_surname.setGeometry(QtCore.QRect(20, 50, 120, 25))
        self.label_surname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_surname.setAlignment(QtCore.Qt.AlignCenter)
        self.label_surname.setObjectName("label_4")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(160, 50, 120, 25))
        self.label_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_5")
        self.label_patronymic = QtWidgets.QLabel(self.centralwidget)
        self.label_patronymic.setGeometry(QtCore.QRect(300, 50, 120, 25))
        self.label_patronymic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_patronymic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patronymic.setObjectName("label_6")
        self.label_birthday = QtWidgets.QLabel(self.centralwidget)
        self.label_birthday.setGeometry(QtCore.QRect(20, 120, 190, 25))
        self.label_birthday.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_birthday.setAlignment(QtCore.Qt.AlignCenter)
        self.label_birthday.setObjectName("label_7")
        self.label_regnumber = QtWidgets.QLabel(self.centralwidget)
        self.label_regnumber.setGeometry(QtCore.QRect(230, 120, 190, 25))
        self.label_regnumber.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_regnumber.setAlignment(QtCore.Qt.AlignCenter)
        self.label_regnumber.setObjectName("label_8")
        self.label_school_city = QtWidgets.QLabel(self.centralwidget)
        self.label_school_city.setGeometry(QtCore.QRect(20, 235, 120, 25))
        self.label_school_city.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_school_city.setAlignment(QtCore.Qt.AlignCenter)
        self.label_school_city.setObjectName("label_9")
        self.label_school_name = QtWidgets.QLabel(self.centralwidget)
        self.label_school_name.setGeometry(QtCore.QRect(160, 235, 120, 25))
        self.label_school_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_school_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_school_name.setObjectName("label_10")
        self.label_school_number = QtWidgets.QLabel(self.centralwidget)
        self.label_school_number.setGeometry(QtCore.QRect(300, 235, 120, 25))
        self.label_school_number.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_school_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_school_number.setObjectName("label_11")
        self.label_school_end = QtWidgets.QLabel(self.centralwidget)
        self.label_school_end.setGeometry(QtCore.QRect(20, 305, 120, 25))
        self.label_school_end.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_school_end.setAlignment(QtCore.Qt.AlignCenter)
        self.label_school_end.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 420, 120, 25))
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(160, 420, 120, 25))
        self.label_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(300, 420, 120, 25))
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 490, 190, 25))
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(230, 490, 190, 25))
        self.label_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.Button_save_anketa = QtWidgets.QPushButton(self.centralwidget)
        self.Button_save_anketa.setGeometry(QtCore.QRect(20, 550, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Button_save_anketa.setFont(font)
        self.Button_save_anketa.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)


        # self.input_proff = QtWidgets.QComboBox(self.centralwidget)
        # self.input_proff.setGeometry(QtCore.QRect(230, 515, 190, 20))
        # self.input_proff.setText("")
        # self.input_proff.set
        # self.input_proff.setObjectName("lineEdit_14")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(230, 515, 190, 20))
        self.comboBox.setObjectName("comboBox")
        self.choice_proff()
        # self.comboBox.addItem("sekond")
        # self.comboBox.addItem("first")

        self.Button_save_anketa.clicked.connect(self.save)  #++

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Анкета абитуриента"))
        self.check_achievements.setText(_translate("MainWindow", "Достижения"))
        self.label_2.setText(_translate("MainWindow", "Оконченное среднее учебное заведение "))
        self.label_3.setText(_translate("MainWindow", "Адрес проживания"))
        self.label_surname.setText(_translate("MainWindow", "Фамилия"))
        self.label_name.setText(_translate("MainWindow", "Имя"))
        self.label_patronymic.setText(_translate("MainWindow", "Отчество"))
        self.label_birthday.setText(_translate("MainWindow", "Дата рождения"))
        self.label_regnumber.setText(_translate("MainWindow", "регистрационный номер"))
        self.label_school_city.setText(_translate("MainWindow", "Город"))
        self.label_school_name.setText(_translate("MainWindow", "название"))
        self.label_school_number.setText(_translate("MainWindow", "номер"))
        self.label_school_end.setText(_translate("MainWindow", "дата окончания"))
        self.label_13.setText(_translate("MainWindow", "Город"))
        self.label_14.setText(_translate("MainWindow", "улица"))
        self.label_15.setText(_translate("MainWindow", "номер дома"))
        self.label_16.setText(_translate("MainWindow", "Телефон для связи"))
        self.label_17.setText(_translate("MainWindow", "выбранная специальность"))
        self.Button_save_anketa.setText(_translate("MainWindow", "Сохранить"))

        # self.comboBox.setItemText(0, _translate("MainWindow", "gthdsq"))
        # self.comboBox.setItemText(1, _translate("MainWindow", "yjugjkh"))
        # self.comboBox.setItemText(2, _translate("MainWindow", "tgyuytu"))

    def choice_proff(self):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        resultset = cursor.execute('''SELECT * FROM Справочник_специальностей''')
        rows = resultset.fetchall()
        for i, row in enumerate(rows):  #
            self.comboBox.addItem(row[1])
        connection.commit()
        connection.close()

    def save(self): #+++
        surname = self.input_surname.text()
        name = self.input_name.text()
        patronymic = self.input_patronymic.text()
        birthday = self.input_birthday.text()
        regnumber = self.input_regnumber.text()
        school_city = self.input_school_city.text()
        school_name = self.input_school_name.text()
        school_number = self.input_school_number.text()
        school_end = self.input_school_end.text()
        city = self.input_city.text()
        street = self.input_street.text()
        number = self.input_number.text()
        telephone = self.input_telephone.text()
        proff = self.comboBox.currentText()
        achievements = self.check_achievements.checkState() == QtCore.Qt.CheckState.Checked #+++

        anketa = Anketa(surname, name, patronymic, birthday, regnumber, school_city, school_name, school_number,
                        school_end, city, street, number, telephone, proff, achievements)

        self.anketaService.save(anketa)
        self.action()
        self.close()


class AnketaService:
    def __init__(self):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        cursor.execute('''CREATE TABLE IF NOT EXISTS Список_абитуриентов(
                      регистрационный_номер INTEGER primary key, 
                      фамилия TEXT,
                      имя TEXT,
                      отчество TEXT, 
                      дата_рождения DATE, 
                      школа_город TEXT,
                      школа_название TEXT,
                      школа_номер TEXT,
                      дата_окончания DATE,
                      достижения BOOL,
                      город_проживания TEXT,
                      улица TEXT,
                      номер_дома TEXT,
                      телефон_для_связи TEXT,
                      выбранная_специальность TEXT)''')
        connection.commit()
        connection.close()

    def save(self, anketa):
        connection = sqlite3.connect('приемная_коммиссия.db')
        cursor = connection.cursor()
        sql = f'''INSERT INTO Список_абитуриентов VALUES ({anketa.regnumber}, '{anketa.surname}', 
        '{anketa.name}', '{anketa.patronymic}', '{anketa.birthday}', '{anketa.school_city}',
         '{anketa.school_name}', '{anketa.school_number}', '{anketa.school_end}', {anketa.achievements}, 
         '{anketa.city}', '{anketa.street}', '{anketa.number}', '{anketa.telephone}', '{anketa.proff}' )'''

        cursor.execute(sql)
        resultset = cursor.execute(''' SELECT * FROM Список_абитуриентов''')

        print(resultset.fetchall())
        connection.commit()
        connection.close()


class Anketa:
    def __init__(self, surname, name, patronymic, birthday, regnumber, school_city, school_name, school_number,
                        school_end, city, street, number, telephone, proff, achievements):
        self.achievements = achievements
        self.proff = proff
        self.telephone = telephone
        self.number = number
        self.street = street
        self.city = city
        self.school_end = school_end
        self.school_number = school_number
        self.school_name = school_name
        self.surname = surname
        self.name = name
        self.patronymic = patronymic
        self.birthday = birthday
        self.regnumber = regnumber
        self.school_city = school_city





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Anketa()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
